// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PostTipo1DocumentDataSlicesSlice = never;

/**
 * Content for Post tipo 1 documents
 */
interface PostTipo1DocumentData {
  /**
   * Slice Zone field in *Post tipo 1*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post_tipo_1.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PostTipo1DocumentDataSlicesSlice> /**
   * Meta Title field in *Post tipo 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post_tipo_1.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Post tipo 1*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: post_tipo_1.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Post tipo 1*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post_tipo_1.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Post tipo 1 document from Prismic
 *
 * - **API ID**: `post_tipo_1`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostTipo1Document<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PostTipo1DocumentData>,
    "post_tipo_1",
    Lang
  >;

export type AllDocumentTypes = PostTipo1Document;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      PostTipo1Document,
      PostTipo1DocumentData,
      PostTipo1DocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
